[env:cardputer]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyACM0
lib_deps = 
    m5stack/M5Cardputer@^1.1.0
    jgromes/RadioLib@^6.5.0
build_flags = 
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM